name: Build LaTeX document

on:
  push:
    paths:
      - 'report/**.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report/main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: report-pdf
          path: report/main.pdf

